"""add_completed_field_to_task_model

Revision ID: 71c0d6672908
Revises: 0fc3094e3be3
Create Date: 2025-05-21 01:11:12.860189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c0d6672908'
down_revision: Union[str, None] = '0fc3094e3be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_tasks', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_tasks', 'completed')
    # ### end Alembic commands ###
