/**
 * 学习追踪模块API配置
 * 定义学习追踪相关的API端点
 */
import { API_CONFIG } from '../../../config';

// 学习追踪API端点
export const STUDY_API_CONFIG = {
  // 任务相关
  TASKS: {
    BASE: API_CONFIG.ENDPOINTS.TASKS.BASE,
    DETAIL: API_CONFIG.ENDPOINTS.TASKS.DETAIL,
    COMPLETE: API_CONFIG.ENDPOINTS.TASKS.COMPLETE
  },

  // 计划相关
  PLANS: {
    BASE: API_CONFIG.ENDPOINTS.PLANS.BASE,
    DETAIL: API_CONFIG.ENDPOINTS.PLANS.DETAIL
  },

  // 成就相关
  ACHIEVEMENTS: {
    BASE: API_CONFIG.ENDPOINTS.ACHIEVEMENTS.BASE,
    DETAIL: API_CONFIG.ENDPOINTS.ACHIEVEMENTS.DETAIL,
    UNLOCK: API_CONFIG.ENDPOINTS.ACHIEVEMENTS.UNLOCK
  },

  // 统计相关
  STATISTICS: {
    TOTAL: API_CONFIG.ENDPOINTS.STATISTICS.TOTAL,
    DAILY: API_CONFIG.ENDPOINTS.STATISTICS.DAILY,
    WEEKLY: API_CONFIG.ENDPOINTS.STATISTICS.WEEKLY,
    MONTHLY: API_CONFIG.ENDPOINTS.STATISTICS.MONTHLY,
    HEATMAP: API_CONFIG.ENDPOINTS.STATISTICS.HEATMAP,
    TIME_DISTRIBUTION: API_CONFIG.ENDPOINTS.STATISTICS.TIME_DISTRIBUTION,
    USER_INFO: API_CONFIG.ENDPOINTS.STATISTICS.USER_INFO,
    USER_STATS: API_CONFIG.ENDPOINTS.STATISTICS.USER_STATS
  }
};

export default STUDY_API_CONFIG;
